/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe.inventory.system;

/**
 *
 * @author my
 */
public class Category_based extends javax.swing.JFrame {

    /**
     * Creates new form Category_based
     */
    public Category_based() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt3ingredient = new javax.swing.JLabel();
        txt4ingredient = new javax.swing.JLabel();
        txtdessert = new javax.swing.JLabel();
        txt5ingredient = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt3ingredient.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txt3ingredient.setForeground(new java.awt.Color(85, 42, 25));
        txt3ingredient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt3ingredient.setText("3 INGREDIENT RECIPES");
        getContentPane().add(txt3ingredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 400, -1));

        txt4ingredient.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txt4ingredient.setForeground(new java.awt.Color(85, 42, 25));
        txt4ingredient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt4ingredient.setText("4 INGREDIENT RECIPES");
        getContentPane().add(txt4ingredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 400, -1));

        txtdessert.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtdessert.setForeground(new java.awt.Color(85, 42, 25));
        txtdessert.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdessert.setText("DESSERTS ");
        getContentPane().add(txtdessert, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 400, -1));

        txt5ingredient.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txt5ingredient.setForeground(new java.awt.Color(85, 42, 25));
        txt5ingredient.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt5ingredient.setText("5 INGREDIENT RECIPES");
        getContentPane().add(txt5ingredient, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 400, -1));

        jButton1.setBackground(new java.awt.Color(245, 245, 220));
        jButton1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(85, 42, 25));
        jButton1.setText("-->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(245, 245, 220));
        jButton2.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(85, 42, 25));
        jButton2.setText("-->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, -1, -1));

        jButton3.setBackground(new java.awt.Color(245, 245, 220));
        jButton3.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(85, 42, 25));
        jButton3.setText("-->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, -1, -1));

        jButton4.setBackground(new java.awt.Color(245, 245, 220));
        jButton4.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(85, 42, 25));
        jButton4.setText("-->");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 540, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category_based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category_based().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel txt3ingredient;
    private javax.swing.JLabel txt4ingredient;
    private javax.swing.JLabel txt5ingredient;
    private javax.swing.JLabel txtdessert;
    // End of variables declaration//GEN-END:variables
}
