/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe.inventory.system;

/**
 *
 * @author my
 */
public class Chef_sepcial extends javax.swing.JFrame {

    /**
     * Creates new form Chef_sepcial
     */
    public Chef_sepcial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbreakfast = new javax.swing.JLabel();
        txtbrunch = new javax.swing.JLabel();
        txtdinner = new javax.swing.JLabel();
        txtlunch = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtbreakfast1 = new javax.swing.JLabel();
        txtbrunch1 = new javax.swing.JLabel();
        txtdinner1 = new javax.swing.JLabel();
        txtlunch1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtbreakfast.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtbreakfast.setForeground(new java.awt.Color(85, 42, 25));
        txtbreakfast.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbreakfast.setText("CHEF RANVEER BRAR");

        txtbrunch.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtbrunch.setForeground(new java.awt.Color(85, 42, 25));
        txtbrunch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbrunch.setText("CHEF SANJEEV KAPOOR");

        txtdinner.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtdinner.setForeground(new java.awt.Color(85, 42, 25));
        txtdinner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdinner.setText("CHEF GARIMA GOEL");

        txtlunch.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtlunch.setForeground(new java.awt.Color(85, 42, 25));
        txtlunch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtlunch.setText("CHEF KUNAL KAPOOR");

        jButton1.setBackground(new java.awt.Color(245, 245, 220));
        jButton1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(85, 42, 25));
        jButton1.setText("-->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(245, 245, 220));
        jButton2.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(85, 42, 25));
        jButton2.setText("-->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(245, 245, 220));
        jButton3.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(85, 42, 25));
        jButton3.setText("-->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(245, 245, 220));
        jButton4.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(85, 42, 25));
        jButton4.setText("-->");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtbreakfast1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtbreakfast1.setForeground(new java.awt.Color(85, 42, 25));
        txtbreakfast1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbreakfast1.setText("CHEF VIKAS KHANNA");

        txtbrunch1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtbrunch1.setForeground(new java.awt.Color(85, 42, 25));
        txtbrunch1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbrunch1.setText("BRUNCH");

        txtdinner1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtdinner1.setForeground(new java.awt.Color(85, 42, 25));
        txtdinner1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtdinner1.setText("DINNER");

        txtlunch1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtlunch1.setForeground(new java.awt.Color(85, 42, 25));
        txtlunch1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtlunch1.setText("LUNCH");

        jButton5.setBackground(new java.awt.Color(245, 245, 220));
        jButton5.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(85, 42, 25));
        jButton5.setText("-->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(245, 245, 220));
        jButton6.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(85, 42, 25));
        jButton6.setText("-->");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(245, 245, 220));
        jButton7.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(85, 42, 25));
        jButton7.setText("-->");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(245, 245, 220));
        jButton8.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(85, 42, 25));
        jButton8.setText("-->");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbrunch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlunch, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdinner, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbreakfast1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbrunch1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlunch1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbreakfast1)
                            .addComponent(jButton5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(txtbrunch1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(txtlunch1))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(txtdinner1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbreakfast)
                            .addComponent(jButton1))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(txtbrunch))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(txtlunch))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(txtdinner))))
                .addGap(157, 157, 157))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chef_sepcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chef_sepcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chef_sepcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chef_sepcial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chef_sepcial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel txtbreakfast;
    private javax.swing.JLabel txtbreakfast1;
    private javax.swing.JLabel txtbrunch;
    private javax.swing.JLabel txtbrunch1;
    private javax.swing.JLabel txtdinner;
    private javax.swing.JLabel txtdinner1;
    private javax.swing.JLabel txtlunch;
    private javax.swing.JLabel txtlunch1;
    // End of variables declaration//GEN-END:variables
}
