/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe.inventory.system;
import javax.swing.JLabel;
import dao.usertablequery;


/**
 *
 * @author my
 */
public class Cuisine_Based extends javax.swing.JFrame {
      private JLabel jLabel1 = new JLabel();
private JLabel jLabel2 = new JLabel();
private JLabel jLabel3 = new JLabel();
private JLabel jLabel4 = new JLabel();
private JLabel jLabel5 = new JLabel();
private JLabel jLabel6 = new JLabel();
private JLabel jLabel7 = new JLabel();
private JLabel jLabel8 = new JLabel();
private JLabel jLabel9 = new JLabel();
private JLabel jLabel10 = new JLabel();

    /**
     * Creates new form Cuisine_Based
     */
    public Cuisine_Based() {
        initComponents();
    }
  
private void inspectJLabels() {
    // Iterate through the JLabels and print their text
    System.out.println("Recipe names for Mexican cuisine:");
    System.out.println("---------------------------------");
    System.out.println("1. " + jLabel1.getText());
    System.out.println("2. " + jLabel2.getText());
    System.out.println("3. " + jLabel3.getText());
    System.out.println("4. " + jLabel4.getText());
    System.out.println("5. " + jLabel5.getText());
    System.out.println("6. " + jLabel6.getText());
    System.out.println("7. " + jLabel7.getText());
    System.out.println("8. " + jLabel8.getText());
    System.out.println("9. " + jLabel9.getText());
    System.out.println("10. " + jLabel10.getText());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtindian = new javax.swing.JLabel();
        txteuropian = new javax.swing.JLabel();
        txtmexican = new javax.swing.JLabel();
        txtjapanese = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtkorean = new javax.swing.JLabel();
        txtcontinental = new javax.swing.JLabel();
        txtitalian = new javax.swing.JLabel();
        txtamerican = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtindian.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtindian.setForeground(new java.awt.Color(85, 42, 25));
        txtindian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtindian.setText("INDIAN");

        txteuropian.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txteuropian.setForeground(new java.awt.Color(85, 42, 25));
        txteuropian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txteuropian.setText("EUROPIAN");

        txtmexican.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtmexican.setForeground(new java.awt.Color(85, 42, 25));
        txtmexican.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtmexican.setText("MEXICAN");

        txtjapanese.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtjapanese.setForeground(new java.awt.Color(85, 42, 25));
        txtjapanese.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtjapanese.setText("JAPANESE");

        jButton1.setBackground(new java.awt.Color(245, 245, 220));
        jButton1.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(85, 42, 25));
        jButton1.setText("-->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(245, 245, 220));
        jButton2.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(85, 42, 25));
        jButton2.setText("-->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(245, 245, 220));
        jButton3.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(85, 42, 25));
        jButton3.setText("-->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(245, 245, 220));
        jButton4.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(85, 42, 25));
        jButton4.setText("-->");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(245, 245, 220));
        jButton5.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(85, 42, 25));
        jButton5.setText("-->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtkorean.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtkorean.setForeground(new java.awt.Color(85, 42, 25));
        txtkorean.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtkorean.setText("KOREAN");

        txtcontinental.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtcontinental.setForeground(new java.awt.Color(85, 42, 25));
        txtcontinental.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtcontinental.setText("CONTINENTAL");

        txtitalian.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtitalian.setForeground(new java.awt.Color(85, 42, 25));
        txtitalian.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtitalian.setText("ITALIAN");

        txtamerican.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        txtamerican.setForeground(new java.awt.Color(85, 42, 25));
        txtamerican.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtamerican.setText("AMERICAN");

        jButton6.setBackground(new java.awt.Color(245, 245, 220));
        jButton6.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(85, 42, 25));
        jButton6.setText("-->");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(245, 245, 220));
        jButton7.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(85, 42, 25));
        jButton7.setText("-->");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(245, 245, 220));
        jButton8.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(85, 42, 25));
        jButton8.setText("-->");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtindian, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteuropian, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtjapanese, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmexican, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkorean, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontinental, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtamerican, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtitalian, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton5))
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkorean)
                            .addComponent(jButton6))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7)
                            .addComponent(txtcontinental))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8)
                            .addComponent(txtamerican))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(txtitalian)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtindian)
                            .addComponent(jButton1))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(txteuropian))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(txtjapanese))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(txtmexican))))
                .addGap(151, 151, 151))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new select_recipe().setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       setVisible(false);
    new mexican_recipes().setVisible(true);
    String[] mexicanRecipeNames = usertablequery.fetchAndDisplayRecipes("Mexican");
    mexican_recipes mexicanFrame = new mexican_recipes(mexicanRecipeNames);
    mexicanFrame.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuisine_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuisine_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuisine_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuisine_Based.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuisine_Based().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel txtamerican;
    private javax.swing.JLabel txtcontinental;
    private javax.swing.JLabel txteuropian;
    private javax.swing.JLabel txtindian;
    private javax.swing.JLabel txtitalian;
    private javax.swing.JLabel txtjapanese;
    private javax.swing.JLabel txtkorean;
    private javax.swing.JLabel txtmexican;
    // End of variables declaration//GEN-END:variables
}
