/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe.inventory.system;
import model.Useruser;
import dao.usertablequery;

/**
 *
 * @author my
 */
public class Home_tab extends javax.swing.JFrame{
   

    public Home_tab() {
       
        initComponents();
       // customizeUI();
    }

//    private void customizeUI() {
//        // Here you can customize the UI based on the loggedInUser data
//        // For example:
//        String username = loggedInUser.getUsername();
//        // Update labels, buttons, or any other components accordingly
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnaboutus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnrecipe = new javax.swing.JButton();
        btnshop = new javax.swing.JButton();
        btnrecipeoftheday = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnaboutus.setBackground(new java.awt.Color(245, 245, 220));
        btnaboutus.setFont(new java.awt.Font("SNDOT-Surekh", 1, 36)); // NOI18N
        btnaboutus.setForeground(new java.awt.Color(85, 42, 25));
        btnaboutus.setText("ABOUT US");
        btnaboutus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaboutusActionPerformed(evt);
            }
        });
        btnaboutus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnaboutusKeyReleased(evt);
            }
        });
        getContentPane().add(btnaboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 230, 70));

        jButton1.setBackground(new java.awt.Color(245, 245, 220));
        jButton1.setFont(new java.awt.Font("SNDOT-Surekh", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(85, 42, 25));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 230, 70));

        btnrecipe.setBackground(new java.awt.Color(245, 245, 220));
        btnrecipe.setFont(new java.awt.Font("SNDOT-Surekh", 1, 36)); // NOI18N
        btnrecipe.setForeground(new java.awt.Color(85, 42, 25));
        btnrecipe.setText("SHOP");
        btnrecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecipeActionPerformed(evt);
            }
        });
        getContentPane().add(btnrecipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 510, 200, 70));

        btnshop.setBackground(new java.awt.Color(245, 245, 220));
        btnshop.setFont(new java.awt.Font("SNDOT-Surekh", 1, 36)); // NOI18N
        btnshop.setForeground(new java.awt.Color(85, 42, 25));
        btnshop.setText("RECIPES");
        btnshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshopActionPerformed(evt);
            }
        });
        getContentPane().add(btnshop, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, 200, 70));

        btnrecipeoftheday.setBackground(new java.awt.Color(245, 245, 220));
        btnrecipeoftheday.setFont(new java.awt.Font("SNDOT-Surekh", 1, 36)); // NOI18N
        btnrecipeoftheday.setForeground(new java.awt.Color(85, 42, 25));
        btnrecipeoftheday.setText("RECIPE OF THE DAY");
        btnrecipeoftheday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecipeofthedayActionPerformed(evt);
            }
        });
        getContentPane().add(btnrecipeoftheday, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 650, 910, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ABOUT.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, -60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaboutusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnaboutusKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnaboutusKeyReleased

    private void btnaboutusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaboutusActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new About_us().setVisible(true);
    }//GEN-LAST:event_btnaboutusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Search().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnshopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshopActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        new Recipe().setVisible(true);
    }//GEN-LAST:event_btnshopActionPerformed

    private void btnrecipeofthedayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecipeofthedayActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Recipeoftheday().setVisible(true);
    }//GEN-LAST:event_btnrecipeofthedayActionPerformed

    private void btnrecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecipeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Shop().setVisible(true);
    }//GEN-LAST:event_btnrecipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                String username = "txtusername";
//                 Useruser loggedInUser = usertablequery.getUserData(username);
                new Home_tab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaboutus;
    private javax.swing.JButton btnrecipe;
    private javax.swing.JButton btnrecipeoftheday;
    private javax.swing.JButton btnshop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
