/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recipe.inventory.system;

/**
 *
 * @author my
 */
public class Recipe extends javax.swing.JFrame {

    /**
     * Creates new form Recipe
     */
    public Recipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnchefspecial = new javax.swing.JButton();
        btnmealbased = new javax.swing.JButton();
        btncategorybased = new javax.swing.JButton();
        btncuisinebased = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnchefspecial.setBackground(new java.awt.Color(245, 245, 220));
        btnchefspecial.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        btnchefspecial.setText("-->");
        btnchefspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchefspecialActionPerformed(evt);
            }
        });
        getContentPane().add(btnchefspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 720, -1, 60));

        btnmealbased.setBackground(new java.awt.Color(245, 245, 220));
        btnmealbased.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        btnmealbased.setText("-->");
        btnmealbased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmealbasedActionPerformed(evt);
            }
        });
        getContentPane().add(btnmealbased, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 610, -1, 60));

        btncategorybased.setBackground(new java.awt.Color(245, 245, 220));
        btncategorybased.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        btncategorybased.setText("-->");
        btncategorybased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategorybasedActionPerformed(evt);
            }
        });
        getContentPane().add(btncategorybased, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 480, -1, 60));

        btncuisinebased.setBackground(new java.awt.Color(245, 245, 220));
        btncuisinebased.setFont(new java.awt.Font("Swis721 BdCnOul BT", 1, 36)); // NOI18N
        btncuisinebased.setText("-->");
        btncuisinebased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuisinebasedActionPerformed(evt);
            }
        });
        btncuisinebased.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btncuisinebasedKeyReleased(evt);
            }
        });
        getContentPane().add(btncuisinebased, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 360, 90, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recipee.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncategorybasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategorybasedActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        new Category_based().setVisible(true);
    }//GEN-LAST:event_btncategorybasedActionPerformed

    private void btncuisinebasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuisinebasedActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Cuisine_Based().setVisible(true);
    }//GEN-LAST:event_btncuisinebasedActionPerformed

    private void btnmealbasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmealbasedActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        new Meal_based().setVisible(true);
    }//GEN-LAST:event_btnmealbasedActionPerformed

    private void btnchefspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchefspecialActionPerformed
        // TODO add your handling code here:
          setVisible(false);
        new Chef_sepcial().setVisible(true);
    }//GEN-LAST:event_btnchefspecialActionPerformed

    private void btncuisinebasedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncuisinebasedKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btncuisinebasedKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncategorybased;
    private javax.swing.JButton btnchefspecial;
    private javax.swing.JButton btncuisinebased;
    private javax.swing.JButton btnmealbased;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
